<?php

/**
 * Returns a subscription form for Insights mailchimp list signup form.
 */
function gsb_rethink_insights_signup_form($form, &$form_state) {
  $form['#attributes'] = array('class' => array('insights-signup-form-wrapper'));

  $form['label'] = array(
    '#markup' => '<div class="signup-text">Sign up for more insights & ideas.</div>',
    '#prefix' => '<div id="insights-signup-form">',
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t("Email Address"),
    '#title_display' => 'none',
    '#attributes' => array(
      'placeholder' => t('email address'),
    ),
    '#required' => TRUE,

  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#weight' => 10,
    '#value' => t('Go'),
    '#ajax' => array(
      'callback' => 'gsb_rethink_insights_signup_submit_callback',
      'wrapper' => 'insights-signup-form',
      'method' => 'replace',
      'effect' => 'fade',
    ),
    '#suffix' => '</div>',
  );

  return $form;
}

/**
 * Submit handler to add user to insights mailing list on subscription form submission.
 */
function gsb_rethink_insights_signup_submit_callback($form, &$form_state) {
  $list_id = variable_get('gsb_insights_mailchimp_list_id', '');
  $email = $form_state['values']['email'];

  if (mailchimp_is_subscribed($list_id, $email)) {
    $message = '<div class="signup-text">' . t('Thank you! You have previously signed up. If you are not receiving Re:Think, !link.' .'</div>', array('!link' => l('update your settings', 'http://google.com')));
  }
  else {
    $result = mailchimp_subscribe($list_id, $email, $mergevars = NULL, $double_id = TRUE, $send_welcome = TRUE);
    if (empty($result)) {
      $message = '<div class="signup-text">' . t('There was a problem with your newsletter signup.') . '</div>';
    } else {
      $message = '<div class="signup-text">' . t('Thank you! Please check your inbox to confirm your email address.') . '</div>';
    }
  }

  $element = array(
    '#markup' => $message,
  );

  return $element;
}

/**
 * Implements hook_node_view().
 *  - Add insights signup form extra field.
 */
function gsb_rethink_node_view($node, $view_mode, $langcode) {
  // If this field is not configured for this view mode, skip it.
  $fields = field_extra_fields_get_display('node', $node->type, $view_mode);
  if (empty($fields['gsb_feature_idea_story_ct_explore_more']['visible'])) {
    return;
  }

  // Insights Signup form uses mailchimp module to connect to Mailchimp API.
  if (module_exists('mailchimp')) {
    $node->content['insights_signup_form'] = drupal_get_form('gsb_rethink_insights_signup_form');
  }
}

/**
 * Implements hook_form_alter().
 */
function gsb_rethink_form_alter(&$form, &$form_state) {
  if ($form['#form_id'] == 'gsb_feature_idea_story_display_config_top_stories') {
    $form['gsb_insights_mailchimp_list_id'] = array(
      '#type' => 'textfield',
      '#title' => t('Rethink signup list id'),
      '#default_value' => variable_get('gsb_insights_mailchimp_list_id', '8fb9107534'),
      '#weight' => -10,
    );

    $form['#submit'][] = 'gsb_rethink_settings_form_submit';
  }
}

/**
 * Submit handler for gsb_feature_idea_story_display_config_top_stories.
 *  - Save rethink list id in variable.
 */
function gsb_rethink_settings_form_submit($form, &$form_state) {
  variable_set('gsb_insights_mailchimp_list_id', $form_state['values']['gsb_insights_mailchimp_list_id']);
}
